name: BuildAndPublish
on: push
jobs:
  BuildAndPublish:
    name: BuildAndPublish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Docker Build Tag and Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: polatengin/moscow
        tags: latest
